name: Node.js CI Pipeline

on:
  push:
    branches: [master]
    
  pull_request: 
    branches: [master]

jobs:
  build:
    name: Install dependencies and build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26
      
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  docker-build-push:
    name: Build Docker Image and Push to ECR
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::399894608127:role/github-actions-ssm
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  # test-healthcheck:
  #   name: Test to check the health of application
  #   needs: docker-build-push
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Check Health Endpoint
  #       run: |
  #         # Consider changing the IP if it needs to match your EC2 instance dynamically
  #         STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://13.201.129.200/node-app-1/api/health)
  #         echo "Received status code: $STATUS_CODE"
          
  #         if [ "$STATUS_CODE" -eq 500 ]; then
  #           echo "Health check failed with status code 500! Terminating pipeline."
  #           exit 1
  #         else
  #           echo "Health check passed with status code $STATUS_CODE."
  #         fi

  deploy:
    name: Deploy on EC2 via SSM
    needs: docker-build-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::399894608127:role/github-actions-ssm
          aws-region: ap-south-1

      - name: Run Deployment via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --targets "Key=tag:purpose,Values=abacus-task-1" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":["aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 399894608127.dkr.ecr.ap-south-1.amazonaws.com","cd /var/abacus-projects/simple-react-full-stack","docker compose up -d"]}' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          # Wait for the command to complete across all targets
          while true; do
            STATUS=$(aws ssm list-commands --command-id "$COMMAND_ID" --query "Commands[0].Status" --output text)
            if [[ "$STATUS" == "Success" || "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
              break
            fi
            sleep 5
          done

          echo "Overall Status: $STATUS"
          echo "----- OUTPUT -----"
          aws ssm list-command-invocations \
            --command-id "$COMMAND_ID" \
            --details \
            --query "CommandInvocations[*].CommandPlugins[*].Output" \
            --output text

          if [ "$STATUS" != "Success" ]; then
            echo "----- ERROR: Command did not succeed on all instances -----"
            exit 1
          fi